# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_truffleruby:
    macos:
        xcode: "14.2.0"

    steps:
      - checkout
      - run:
          name: Turn off brew analytics
          command: echo 'export HOMEBREW_NO_ANALYTICS=1' "$BASH_ENV"
      - run: 
          name: setup env
          command: echo 'export HOMEBREW_CASK_OPTS="/usr/local"' >> "$BASH_ENV"
      - run: 
          name: setup env
          command: echo 'export SYSTEM_RUBY="/usr/bin/ruby"' >> "$BASH_ENV"
      - run: 
          name: setup env
          command: echo 'export OPENSSL_DIR="/usr/local/opt/openssl@3"' >> "$BASH_ENV"
      - run:
          name: install dependencies
          command: "brew install cmake ninja dmd zstd java openssl libyaml"
      - run:
          name: setup env
          command: echo 'export PATH="$HOME/truffleruby/bin/jt:$PATH"' >> "$BASH_ENV"
      - run:
          name: tell yes
          command: echo 'export JT_IMPORTS_DONT_ASK=0' >> "$BASH_ENV"
      - run:
          name: build truffleruby
          command: bin/jt build --env native
      - run:
          name: compress
          command: cd .. && tar -cf truffleruby.tar truffleruby
      - run:
          name: compress zstd
          command: zstd truffleruby.tar
      - store_artifacts:
          path: truffleruby.tar.zst
          destination: truffleruby


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  truffleruby_workflow:
    jobs:
      - build_truffleruby
